# -*- mode: ruby -*-
# vi: set ft=ruby :

##########################
# vagrant全体設定
# OS: CentOS6.5
##########################

Vagrant.configure(2) do |config|
  # デフォルトでrootログインしたい場合に有効にする
  # config.ssh.username = 'root'
  # config.ssh.password = 'vagrant'
  # config.ssh.insert_key = 'true'

  # BOX名
  config.vm.box = "agera-centos65"

  # CentOS6.5
  #config.vm.box_url = "http://www.lyricalsoftware.com/downloads/centos65.box"
  config.vm.box_url = "https://googledrive.com/host/0B4tZlTbOXHYWVGpHRWZuTThGVUE/centos65_virtualbox_50G.box"

  # ミドルウェアインストールのbash
  config.vm.provision :shell, :privileged => false, :path => "vagrant-machine-setup.sh"
  config.vm.provision :shell, :privileged => false, :path => "vagrant-machine-run.sh",run: "always"

  # VMのIPアドレス
  config.vm.network :private_network, ip: "192.168.33.11"

  # SSH設定. デフォルトはfalse
  # config.ssh.forward_agent = true

  # VMとローカルの同期するディレクトリ
  config.vm.synced_folder "../", "/dev_root", create: true
end
